#!/usr/bin/env node

/**
 * Build humanitz-template.db — pre-seeded SQLite database with all game
 * reference data (718 items, 122 buildings, 154 recipes, etc.).
 *
 * This is a dev-only build tool. The template DB is committed to git and
 * shipped with releases. On first run, database.js copies it as the starting
 * point for a user's humanitz.db, eliminating the need for game-tables-raw.json
 * at runtime.
 *
 * Usage:
 *   node scripts/build-template-db.js
 *   npm run build:template
 *
 * Requires: data/game-tables-raw.json (22 MB, from UE4 pak extraction)
 */

/* eslint-disable @typescript-eslint/no-require-imports */
import path from 'path';
import fs from 'fs';
import Database from 'better-sqlite3';

const TEMPLATE_PATH = path.join(__dirname, '..', '..', 'data', 'humanitz-template.db');
const RAW_JSON_PATH = path.join(__dirname, '..', '..', 'data', 'game-tables-raw.json');

// Verify raw JSON exists (needed for extraction)
if (!fs.existsSync(RAW_JSON_PATH)) {
  console.error('[build-template] ERROR: data/game-tables-raw.json not found.');
  console.error('  This file is required to extract game data for the template DB.');
  console.error('  It is generated by the UE4 pak extraction tools in tools/.');
  process.exit(1);
}

// Remove old template if it exists
if (fs.existsSync(TEMPLATE_PATH)) {
  fs.unlinkSync(TEMPLATE_PATH);
  console.log('[build-template] Removed existing template DB');
}

// Create fresh DB with schema + seed all game reference data
const HumanitZDB = require('./database') as new (opts: { dbPath: string; label: string }) => Record<string, unknown>;
const gameReference = require('../parsers/game-reference') as { seed: (db: Record<string, unknown>) => void };

const db = new HumanitZDB({ dbPath: TEMPLATE_PATH, label: 'TEMPLATE' });
(db['init'] as () => void)();
gameReference.seed(db);

// Stamp the template with build metadata
(db['setMeta'] as (k: string, v: string) => void)('template_built_at', new Date().toISOString());
(db['setMeta'] as (k: string, v: string) => void)(
  'template_schema_version',
  String((require('./schema') as { SCHEMA_VERSION: number }).SCHEMA_VERSION),
);

// Verify row counts
const handle = db['db'] as Database.Database;
const tableNames = [
  'game_items',
  'game_buildings',
  'game_recipes',
  'game_loot_pools',
  'game_loot_pool_items',
  'game_vehicles_ref',
  'game_professions',
  'game_afflictions',
  'game_skills',
  'game_challenges',
  'game_loading_tips',
  'game_server_setting_defs',
  'game_car_upgrades',
  'game_ammo_types',
  'game_repair_data',
  'game_furniture',
  'game_traps',
  'game_sprays',
  'game_animals',
  'game_crops',
  'game_lore',
  'game_quests',
  'game_spawn_locations',
] as const;

const counts: Record<string, number> = {};
for (const table of tableNames) {
  counts[table] = (handle.prepare(`SELECT COUNT(*) as n FROM ${table}`).get() as { n: number }).n;
}

(db['close'] as () => void)();

// VACUUM to minimize file size
const vacDb = new Database(TEMPLATE_PATH);
vacDb.exec('VACUUM');
vacDb.close();

const sizeBytes = fs.statSync(TEMPLATE_PATH).size;
const sizeMB = (sizeBytes / 1024 / 1024).toFixed(2);
const totalRows = Object.values(counts).reduce((a, b) => a + b, 0);

console.log('');
console.log('  Template DB built successfully');
console.log(`  Path: data/humanitz-template.db`);
console.log(`  Size: ${sizeMB} MB (vs 22 MB game-tables-raw.json)`);
console.log(`  Tables: ${String(Object.keys(counts).length)} game reference tables`);
console.log(`  Rows: ${String(totalRows)} total`);

for (const [table, count] of Object.entries(counts)) {
  const name = table.replace('game_', '');
  console.log(`  ${name}: ${String(count)} rows`);
}
