import type { Response } from 'express';

const API_ERRORS = {
  RATE_LIMITED: 'RATE_LIMITED',
  PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
  INVALID_BOUNDS: 'INVALID_BOUNDS',
  MISSING_POINTS: 'MISSING_POINTS',
  POINTS_TOO_CLOSE: 'POINTS_TOO_CLOSE',
  MISSING_STEAM_ID: 'MISSING_STEAM_ID',
  INVALID_STEAM_ID_FORMAT: 'INVALID_STEAM_ID_FORMAT',
  MISSING_MESSAGE: 'MISSING_MESSAGE',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  MESSAGE_EMPTY_AFTER_SANITIZATION: 'MESSAGE_EMPTY_AFTER_SANITIZATION',
  NO_DATABASE: 'NO_DATABASE',
  NO_SQL_PROVIDED: 'NO_SQL_PROVIDED',
  ONLY_SELECT_ALLOWED: 'ONLY_SELECT_ALLOWED',
  QUERY_CONTAINS_DISALLOWED_KEYWORDS: 'QUERY_CONTAINS_DISALLOWED_KEYWORDS',
  INSTANCE_NOT_FOUND: 'INSTANCE_NOT_FOUND',
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  NEED_FINGERPRINT_OR_ITEM_NAME: 'NEED_FINGERPRINT_OR_ITEM_NAME',
  INVALID_TABLE_NAME: 'INVALID_TABLE_NAME',
  TABLE_NOT_QUERYABLE: 'TABLE_NOT_QUERYABLE',
  MISSING_COMMAND: 'MISSING_COMMAND',
  COMMAND_TOO_LONG: 'COMMAND_TOO_LONG',
  COMMAND_EMPTY_AFTER_SANITIZATION: 'COMMAND_EMPTY_AFTER_SANITIZATION',
  COMMAND_BLOCKED_FOR_SAFETY: 'COMMAND_BLOCKED_FOR_SAFETY',
  SAVE_SERVICE_NOT_AVAILABLE: 'SAVE_SERVICE_NOT_AVAILABLE',
  INVALID_ACTION: 'INVALID_ACTION',
  BACKUP_FAILED: 'BACKUP_FAILED',
  DOCKER_COMMAND_FAILED: 'DOCKER_COMMAND_FAILED',
  FAILED_TO_READ_SETTINGS: 'FAILED_TO_READ_SETTINGS',
  NO_SETTINGS_AVAILABLE_SFTP_NOT_CONFIGURED: 'NO_SETTINGS_AVAILABLE_SFTP_NOT_CONFIGURED',
  MISSING_SETTINGS_OBJECT: 'MISSING_SETTINGS_OBJECT',
  CANNOT_WRITE_PROTECTED_SETTINGS: 'CANNOT_WRITE_PROTECTED_SETTINGS',
  INVALID_VALUE_CONTAINS_ILLEGAL_CHARACTERS: 'INVALID_VALUE_CONTAINS_ILLEGAL_CHARACTERS',
  SFTP_NOT_CONFIGURED: 'SFTP_NOT_CONFIGURED',
  FAILED_TO_SAVE_SETTINGS: 'FAILED_TO_SAVE_SETTINGS',
  RESTART_TIMES_INVALID: 'RESTART_TIMES_INVALID',
  INVALID_TIME_FORMAT: 'INVALID_TIME_FORMAT',
  PROFILE_SETTINGS_MUST_BE_OBJECT: 'PROFILE_SETTINGS_MUST_BE_OBJECT',
  INVALID_PROFILE_VALUE_TYPE: 'INVALID_PROFILE_VALUE_TYPE',
  SERVER_NOT_FOUND: 'SERVER_NOT_FOUND',
  FAILED_TO_SAVE: 'FAILED_TO_SAVE',
  ENV_FILE_NOT_FOUND: 'ENV_FILE_NOT_FOUND',
  FAILED_TO_SAVE_SCHEDULE: 'FAILED_TO_SAVE_SCHEDULE',
  SERVER_NOT_FOUND_IN_SERVERS_JSON: 'SERVER_NOT_FOUND_IN_SERVERS_JSON',
  FAILED_TO_READ_BOT_CONFIG: 'FAILED_TO_READ_BOT_CONFIG',
  MISSING_CHANGES_OBJECT: 'MISSING_CHANGES_OBJECT',
  CANNOT_MODIFY_READ_ONLY_KEYS: 'CANNOT_MODIFY_READ_ONLY_KEYS',
  INVALID_VALUE_CONTAINS_NEWLINE: 'INVALID_VALUE_CONTAINS_NEWLINE',
  VALUE_TOO_LONG: 'VALUE_TOO_LONG',
  FAILED_TO_SAVE_SERVER_CONFIG: 'FAILED_TO_SAVE_SERVER_CONFIG',
  FAILED_TO_SAVE_BOT_CONFIG: 'FAILED_TO_SAVE_BOT_CONFIG',
  DATABASE_NOT_AVAILABLE: 'DATABASE_NOT_AVAILABLE',
  INVALID_FLAG_ID: 'INVALID_FLAG_ID',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_SNAPSHOT_ID: 'INVALID_SNAPSHOT_ID',
  SNAPSHOT_NOT_FOUND: 'SNAPSHOT_NOT_FOUND',
  FROM_AND_TO_REQUIRED: 'FROM_AND_TO_REQUIRED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  MISSING_SERVER_NAME: 'MISSING_SERVER_NAME',
  MISSING_RCON_CONFIG: 'MISSING_RCON_CONFIG',
  SERVER_NAME_EXISTS: 'SERVER_NAME_EXISTS',
  CANNOT_DELETE_PRIMARY: 'CANNOT_DELETE_PRIMARY',
  CONFIRM_REQUIRED: 'CONFIRM_REQUIRED',
  INVALID_LIFECYCLE_ACTION: 'INVALID_LIFECYCLE_ACTION',
  CANNOT_CONTROL_PRIMARY: 'CANNOT_CONTROL_PRIMARY',
  SERVER_ALREADY_IN_STATE: 'SERVER_ALREADY_IN_STATE',
  MULTI_SERVER_NOT_AVAILABLE: 'MULTI_SERVER_NOT_AVAILABLE',
  MISSING_SFTP_CONFIG: 'MISSING_SFTP_CONFIG',
  MISSING_CONNECTION_CONFIG: 'MISSING_CONNECTION_CONFIG',
  MAX_CONCURRENT_DISCOVERIES: 'MAX_CONCURRENT_DISCOVERIES',
  DISCOVERY_JOB_NOT_FOUND: 'DISCOVERY_JOB_NOT_FOUND',
  INVALID_BOT_ACTION: 'INVALID_BOT_ACTION',
  BOT_CONTROL_NOT_AVAILABLE: 'BOT_CONTROL_NOT_AVAILABLE',
  CONFIRM_NUKE_REQUIRED: 'CONFIRM_NUKE_REQUIRED',
  BOT_ACTION_PENDING: 'BOT_ACTION_PENDING',
} as const;

const EN_MESSAGES: Record<string, string> = {
  [API_ERRORS.RATE_LIMITED]: 'Too many requests, try again later',
  [API_ERRORS.PLAYER_NOT_FOUND]: 'Player not found',
  [API_ERRORS.INVALID_BOUNDS]: 'Invalid bounds — need xMin, xMax, yMin, yMax as numbers',
  [API_ERRORS.MISSING_POINTS]: 'Need point1 and point2',
  [API_ERRORS.POINTS_TOO_CLOSE]: 'Points too close together — need distinct positions',
  [API_ERRORS.MISSING_STEAM_ID]: 'Missing steamId',
  [API_ERRORS.INVALID_STEAM_ID_FORMAT]: 'Invalid steamId format',
  [API_ERRORS.MISSING_MESSAGE]: 'Missing message',
  [API_ERRORS.MESSAGE_TOO_LONG]: 'Message too long',
  [API_ERRORS.MESSAGE_EMPTY_AFTER_SANITIZATION]: 'Message is empty after sanitization',
  [API_ERRORS.NO_DATABASE]: 'No database',
  [API_ERRORS.NO_SQL_PROVIDED]: 'No SQL provided',
  [API_ERRORS.ONLY_SELECT_ALLOWED]: 'Only SELECT queries are allowed',
  [API_ERRORS.QUERY_CONTAINS_DISALLOWED_KEYWORDS]: 'Query contains disallowed keywords',
  [API_ERRORS.INSTANCE_NOT_FOUND]: 'Instance not found',
  [API_ERRORS.GROUP_NOT_FOUND]: 'Group not found',
  [API_ERRORS.NEED_FINGERPRINT_OR_ITEM_NAME]: 'Need fingerprint or item name',
  [API_ERRORS.INVALID_TABLE_NAME]: 'Invalid table name',
  [API_ERRORS.TABLE_NOT_QUERYABLE]: "Table '{table}' not queryable",
  [API_ERRORS.MISSING_COMMAND]: 'Missing command',
  [API_ERRORS.COMMAND_TOO_LONG]: 'Command too long',
  [API_ERRORS.COMMAND_EMPTY_AFTER_SANITIZATION]: 'Command is empty after sanitization',
  [API_ERRORS.COMMAND_BLOCKED_FOR_SAFETY]: "Command '{cmdWord}' is blocked for safety",
  [API_ERRORS.SAVE_SERVICE_NOT_AVAILABLE]: 'Save service not available',
  [API_ERRORS.INVALID_ACTION]: 'Invalid action: {action}',
  [API_ERRORS.BACKUP_FAILED]: 'Backup failed',
  [API_ERRORS.DOCKER_COMMAND_FAILED]: 'Docker command failed',
  [API_ERRORS.FAILED_TO_READ_SETTINGS]: 'Failed to read settings: {error}',
  [API_ERRORS.NO_SETTINGS_AVAILABLE_SFTP_NOT_CONFIGURED]: 'No settings available (SFTP not configured)',
  [API_ERRORS.MISSING_SETTINGS_OBJECT]: 'Missing settings object',
  [API_ERRORS.CANNOT_WRITE_PROTECTED_SETTINGS]: 'Cannot write protected settings: {keys}',
  [API_ERRORS.INVALID_VALUE_CONTAINS_ILLEGAL_CHARACTERS]: "Invalid value for '{key}': contains illegal characters",
  [API_ERRORS.SFTP_NOT_CONFIGURED]: 'SFTP not configured',
  [API_ERRORS.FAILED_TO_SAVE_SETTINGS]: 'Failed to save settings: {error}',
  [API_ERRORS.RESTART_TIMES_INVALID]: 'restartTimes must be an array of HH:MM strings',
  [API_ERRORS.INVALID_TIME_FORMAT]: 'Invalid time format: {time} (expected HH:MM)',
  [API_ERRORS.PROFILE_SETTINGS_MUST_BE_OBJECT]: "Profile settings for '{name}' must be an object",
  [API_ERRORS.INVALID_PROFILE_VALUE_TYPE]: 'Invalid value type for {name}.{key}',
  [API_ERRORS.SERVER_NOT_FOUND]: 'Server not found',
  [API_ERRORS.FAILED_TO_SAVE]: 'Failed to save: {error}',
  [API_ERRORS.ENV_FILE_NOT_FOUND]: '.env file not found',
  [API_ERRORS.FAILED_TO_SAVE_SCHEDULE]: 'Failed to save schedule: {error}',
  [API_ERRORS.SERVER_NOT_FOUND_IN_SERVERS_JSON]: 'Server not found in servers.json',
  [API_ERRORS.FAILED_TO_READ_BOT_CONFIG]: 'Failed to read bot config: {error}',
  [API_ERRORS.MISSING_CHANGES_OBJECT]: 'Missing changes object',
  [API_ERRORS.CANNOT_MODIFY_READ_ONLY_KEYS]: 'Cannot modify read-only keys: {keys}',
  [API_ERRORS.INVALID_VALUE_CONTAINS_NEWLINE]: "Invalid value for '{key}': contains newline",
  [API_ERRORS.VALUE_TOO_LONG]: "Value for '{key}' too long (max 2000 chars)",
  [API_ERRORS.FAILED_TO_SAVE_SERVER_CONFIG]: 'Failed to save server config: {error}',
  [API_ERRORS.FAILED_TO_SAVE_BOT_CONFIG]: 'Failed to save bot config: {error}',
  [API_ERRORS.DATABASE_NOT_AVAILABLE]: 'Database not available',
  [API_ERRORS.INVALID_FLAG_ID]: 'Invalid flag ID',
  [API_ERRORS.INVALID_STATUS]: 'Invalid status. Must be confirmed, dismissed, or whitelisted',
  [API_ERRORS.INVALID_SNAPSHOT_ID]: 'Invalid snapshot ID',
  [API_ERRORS.SNAPSHOT_NOT_FOUND]: 'Snapshot not found',
  [API_ERRORS.FROM_AND_TO_REQUIRED]: 'from and to are required',
  [API_ERRORS.INTERNAL_SERVER_ERROR]: 'Internal server error',
  [API_ERRORS.MISSING_SERVER_NAME]: 'Server name is required',
  [API_ERRORS.MISSING_RCON_CONFIG]: 'RCON configuration is required (host, port, password)',
  [API_ERRORS.SERVER_NAME_EXISTS]: 'A server with this name already exists',
  [API_ERRORS.CANNOT_DELETE_PRIMARY]: 'Cannot delete the primary server',
  [API_ERRORS.CONFIRM_REQUIRED]: 'Confirmation required — pass ?confirm=true',
  [API_ERRORS.INVALID_LIFECYCLE_ACTION]: 'Invalid action. Must be start, stop, or restart',
  [API_ERRORS.CANNOT_CONTROL_PRIMARY]: 'Cannot control primary server lifecycle from this endpoint',
  [API_ERRORS.SERVER_ALREADY_IN_STATE]: 'Server is already in the requested state',
  [API_ERRORS.MULTI_SERVER_NOT_AVAILABLE]: 'Multi-server manager is not available',
  [API_ERRORS.MISSING_SFTP_CONFIG]: 'SFTP configuration is required (host, user, and password or key)',
  [API_ERRORS.MISSING_CONNECTION_CONFIG]: 'At least one of rcon or sftp configuration is required',
  [API_ERRORS.MAX_CONCURRENT_DISCOVERIES]: 'Too many concurrent discovery jobs (max 3)',
  [API_ERRORS.DISCOVERY_JOB_NOT_FOUND]: 'Discovery job not found or expired',
  [API_ERRORS.INVALID_BOT_ACTION]: 'Invalid action. Must be restart, reimport, factory_reset, or env_sync',
  [API_ERRORS.BOT_CONTROL_NOT_AVAILABLE]: 'Bot control service is not available',
  [API_ERRORS.CONFIRM_NUKE_REQUIRED]: 'Confirmation required \u2014 send { "confirm": "NUKE" } in request body',
  [API_ERRORS.BOT_ACTION_PENDING]: 'Another bot action is already in progress',
};

function sendError(res: Response, code: string, status = 400, details?: Record<string, unknown> | string): void {
  let msg = EN_MESSAGES[code] || code;
  // Interpolate {key} placeholders in error message
  if (details && typeof details === 'object') {
    for (const [k, v] of Object.entries(details)) {
      msg = msg.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
    }
  } else if (typeof details === 'string') {
    // Single-value shorthand: replace first placeholder
    msg = msg.replace(/\{\w+\}/, details);
  }
  res.status(status).json({
    ok: false,
    code,
    error: msg,
    ...(details ? { details } : {}),
  });
}

function sendOk(res: Response, data: Record<string, unknown> = {}): void {
  res.json({ ok: true, ...data });
}

export { API_ERRORS, EN_MESSAGES, sendError, sendOk };
